DEF M_Battle_MessageDenjuuBattlePhrase EQU $02
DEF M_Battle_MessageDenjuuBattlePhraseAlias EQU $04
DEF M_Battle_MessageDenjuuDefected EQU $09

DEF M_Battle_MessageRandomEncounter EQU $0B

DEF M_Battle_MessageBaseStatusConditionContinuing EQU $35
DEF M_Battle_MessageBaseStatusConditionRemoval EQU $44
DEF M_Battle_MessageBaseStatusConditionInflicted EQU $53

DEF M_Battle_MessageStoryEncounter EQU $71

DEF M_Battle_MessageConnectionError EQU $74

DEF M_Battle_MessageNaturalEvoCancel EQU $8E