M_Battle_SpeciesBaseHP EQU $0
M_Battle_SpeciesBaseSpeed EQU $1
M_Battle_SpeciesBaseAttack EQU $2
M_Battle_SpeciesBaseDefense EQU $3
M_Battle_SpeciesBaseDenmaAttack EQU $4
M_Battle_SpeciesBaseDenmaDefense EQU $5
M_Battle_SpeciesMove1 EQU $6
M_Battle_SpeciesMove2 EQU $7
M_Battle_SpeciesMove3 EQU $8
M_Battle_SpeciesMove4 EQU $9 ;Always treated as Denma
M_Battle_SpeciesNaturalEvoLevel EQU $B
M_Battle_SpeciesNaturalEvoSpecies EQU $C
M_Battle_SpeciesType EQU $D
M_Battle_SpeciesMove3Level EQU $E
M_Battle_SpeciesMove4Level EQU $F

M_Battle_SpeciesStride EQU $10