DEF M_Battle_SpeciesBaseHP EQU $0
DEF M_Battle_SpeciesBaseSpeed EQU $1
DEF M_Battle_SpeciesBaseAttack EQU $2
DEF M_Battle_SpeciesBaseDefense EQU $3
DEF M_Battle_SpeciesBaseDenmaAttack EQU $4
DEF M_Battle_SpeciesBaseDenmaDefense EQU $5
DEF M_Battle_SpeciesMove1 EQU $6
DEF M_Battle_SpeciesMove2 EQU $7
DEF M_Battle_SpeciesMove3 EQU $8
DEF M_Battle_SpeciesMove4 EQU $9 ;Always treated as Denma
DEF M_Battle_SpeciesNaturalEvoLevel EQU $B
DEF M_Battle_SpeciesNaturalEvoSpecies EQU $C
DEF M_Battle_SpeciesType EQU $D
DEF M_Battle_SpeciesMove3Level EQU $E
DEF M_Battle_SpeciesMove4Level EQU $F

DEF M_Battle_SpeciesStride EQU $10