DEF M_MetaSpriteConfig_Size EQU $20
DEF M_MetaSpriteConfig1_Count EQU $C
DEF M_MetaSpriteConfig2_Count EQU $8
DEF M_MetaSpriteConfig3_Count EQU $4

DEF M_LCDC_MetaSpriteConfig_HiAttribs EQU $0
DEF M_LCDC_MetaSpriteConfig_Bank EQU $1
DEF M_LCDC_MetaSpriteConfig_Index EQU $2
DEF M_LCDC_MetaSpriteConfig_XOffset EQU $3
DEF M_LCDC_MetaSpriteConfig_YOffset EQU $4
DEF M_LCDC_MetaSpriteConfig_LoAttribs EQU $5
DEF M_LCDC_MetaSpriteConfig_AnimPresent EQU $6
DEF M_LCDC_MetaSpriteConfig_AnimKeyframes EQU $7
DEF M_LCDC_MetaSpriteConfig_AnimCounter EQU $8
DEF M_LCDC_MetaSpriteConfig_AnimPosition EQU $9
DEF M_LCDC_MetaSpriteConfig_AnimStopped EQU $A

DEF M_LCDC_MetaSpriteData_XOffset EQU $0
DEF M_LCDC_MetaSpriteData_YOffset EQU $1
DEF M_LCDC_MetaSpriteData_TileID EQU $2
DEF M_LCDC_MetaSpriteData_AttribMode EQU $3
DEF M_LCDC_MetaSpriteData_Attribs EQU $4

DEF M_LCDC_MetaSpriteData_EntrySize EQU $5

DEF M_LCDC_MetaSpriteData_AttribMode_ConfigAttribs EQU $0
DEF M_LCDC_MetaSpriteData_AttribMode_LocalAttribs EQU $1
DEF M_LCDC_MetaSpriteData_AttribMode_ConfigPalette EQU $2