charmap "!", $21
charmap """, $22
charmap "#", $23
charmap "$", $24
charmap "%", $25
charmap "&", $26
charmap "’", $27
charmap "'", $27
charmap "(", $28
charmap ")", $29
charmap "*", $2A
charmap "+", $2B
charmap ",", $2C
charmap "-", $2D
charmap ".", $2E
charmap "/", $2F
charmap ":", $3A
charmap ";", $3B
charmap "<", $3C
charmap "=", $3D
charmap ">", $3E
charmap "?", $3F
charmap "@", $40
charmap "A", $41
charmap "B", $42
charmap "C", $43
charmap "D", $44
charmap "E", $45
charmap "F", $46
charmap "G", $47
charmap "H", $48
charmap "I", $49
charmap "J", $4A
charmap "K", $4B
charmap "L", $4C
charmap "M", $4D
charmap "N", $4E
charmap "O", $4F
charmap "P", $50
charmap "Q", $51
charmap "R", $52
charmap "S", $53
charmap "T", $54
charmap "U", $55
charmap "V", $56
charmap "W", $57
charmap "X", $58
charmap "Y", $59
charmap "Z", $5A
charmap "[", $5B
charmap "\", $5C
charmap "]", $5D
charmap "^", $5E
charmap "_", $5F
charmap "`", $60
charmap "a", $61
charmap "b", $62
charmap "c", $63
charmap "d", $64
charmap "e", $65
charmap "f", $66
charmap "g", $67
charmap "h", $68
charmap "i", $69
charmap "j", $6A
charmap "k", $6B
charmap "l", $6C
charmap "m", $6D
charmap "n", $6E
charmap "o", $6F
charmap "p", $70
charmap "q", $71
charmap "r", $72
charmap "s", $73
charmap "t", $74
charmap "u", $75
charmap "v", $76
charmap "w", $77
charmap "x", $78
charmap "y", $79
charmap "z", $7A
charmap "{", $7B
charmap "|", $7C
charmap "}", $7D
charmap "~", $7E
charmap "0", $BB
charmap "1", $BC
charmap "2", $BD
charmap "3", $BE
charmap "4", $BF
charmap "5", $C0
charmap "6", $C1
charmap "7", $C2
charmap "8", $C3
charmap "9", $C4
charmap " ", $20