SECTION "SGB Attribute Data (Power Version)", ROMX[$6ED8], BANK[$3]
SGB_AttrFileData::
    INCBIN "versions/power/gfx/sgb/attrfile/00.atf"
    INCBIN "versions/power/gfx/sgb/attrfile/01.atf"
    INCBIN "versions/power/gfx/sgb/attrfile/02.atf"
    INCBIN "versions/power/gfx/sgb/attrfile/03.atf"
    INCBIN "versions/power/gfx/sgb/attrfile/04.atf"
    INCBIN "versions/power/gfx/sgb/attrfile/05.atf"
    INCBIN "versions/power/gfx/sgb/attrfile/06.atf"
    INCBIN "versions/power/gfx/sgb/attrfile/07.atf"
    INCBIN "versions/power/gfx/sgb/attrfile/08.atf"
    INCBIN "versions/power/gfx/sgb/attrfile/09.atf"
    INCBIN "versions/power/gfx/sgb/attrfile/0a.atf"
    INCBIN "versions/power/gfx/sgb/attrfile/0b.atf"
    INCBIN "versions/power/gfx/sgb/attrfile/0c.atf"
    INCBIN "versions/power/gfx/sgb/attrfile/0d.atf"
    INCBIN "versions/power/gfx/sgb/attrfile/0e.atf"
    INCBIN "versions/power/gfx/sgb/attrfile/0f.atf"
    INCBIN "versions/power/gfx/sgb/attrfile/10.atf"
    INCBIN "versions/power/gfx/sgb/attrfile/11.atf"
    INCBIN "versions/power/gfx/sgb/attrfile/12.atf"