SECTION "SGB Attribute Data (Power Version)", ROMX[$5000], BANK[$77]
SGB_AttrFileData::
    INCBIN "build/versions/power/gfx/sgb/attrfile/00.atf"
    INCBIN "build/versions/power/gfx/sgb/attrfile/01.atf"
    INCBIN "build/versions/power/gfx/title/sgb.atf"
    INCBIN "build/gfx/menu/titlemenu.atf"
    INCBIN "build/components/status/status_screen.atf"
    INCBIN "build/components/zukan/zukan_screen.atf"
    INCBIN "build/gfx/menu/titlemenu_inapp.atf"
    INCBIN "build/gfx/menu/pausemenu_inapp.atf"
    INCBIN "build/gfx/menu/pausemenu_inventory.atf"
    INCBIN "build/versions/power/gfx/sgb/attrfile/09.atf"
    INCBIN "build/versions/power/gfx/sgb/attrfile/0a.atf"
    INCBIN "build/versions/power/gfx/sgb/attrfile/0b.atf"
    INCBIN "build/versions/power/gfx/sgb/attrfile/0c.atf"
    INCBIN "build/versions/power/gfx/sgb/attrfile/0d.atf"
    INCBIN "build/versions/power/gfx/sgb/attrfile/0e.atf"
    INCBIN "build/versions/power/gfx/sgb/attrfile/0f.atf"
    INCBIN "build/versions/power/gfx/sgb/attrfile/10.atf"
    INCBIN "build/versions/power/gfx/sgb/attrfile/11.atf"
    INCBIN "build/versions/power/gfx/sgb/attrfile/12.atf"