M_PauseMenu_StateLoadGraphics EQU $00
M_PauseMenu_StateLoadMenuHalves EQU $01
M_PauseMenu_StateLoadPalettes EQU $02
M_PauseMenu_StateLoadDMGCompatibility EQU $03
M_PauseMenu_StateAnimateMenuHalvesIn EQU $04

;Subscreens - each one it's own state machine!
M_PauseMenu_StateContactSubscreen EQU $10
M_PauseMenu_StateMeloDSubscreen EQU $11
M_PauseMenu_StateInventorySubscreen EQU $12
M_PauseMenu_StateSMSSubscreen EQU $13
M_PauseMenu_StateSaveSubscreen EQU $14
M_PauseMenu_StateCallsSubscreen EQU $16