INCLUDE "telefang.inc"

SECTION "Item Graphics Bank 0", ROMX[$4000], BANK[$2B]
PauseMenu_Items0::
    INCBIN "build/gfx/items/0/0.2bpp"
    INCBIN "build/gfx/items/0/1.2bpp"
    INCBIN "build/gfx/items/0/2.2bpp"
    INCBIN "build/gfx/items/0/3.2bpp"
    INCBIN "build/gfx/items/0/4.2bpp"
    INCBIN "build/gfx/items/0/5.2bpp"
    INCBIN "build/gfx/items/0/6.2bpp"
    INCBIN "build/gfx/items/0/7.2bpp"
    INCBIN "build/gfx/items/0/8.2bpp"
    INCBIN "build/gfx/items/0/9.2bpp"
    INCBIN "build/gfx/items/0/10.2bpp"
    INCBIN "build/gfx/items/0/11.2bpp"
    INCBIN "build/gfx/items/0/12.2bpp"
    INCBIN "build/gfx/items/0/13.2bpp"
    INCBIN "build/gfx/items/0/14.2bpp"
    INCBIN "build/gfx/items/0/15.2bpp"
    INCBIN "build/gfx/items/0/16.2bpp"
    INCBIN "build/gfx/items/0/17.2bpp"
    INCBIN "build/gfx/items/0/18.2bpp"
    INCBIN "build/gfx/items/0/19.2bpp"
    INCBIN "build/gfx/items/0/20.2bpp"
    INCBIN "build/gfx/items/0/21.2bpp"
    INCBIN "build/gfx/items/0/22.2bpp"
    INCBIN "build/gfx/items/0/23.2bpp"
    INCBIN "build/gfx/items/0/24.2bpp"
    INCBIN "build/gfx/items/0/25.2bpp"
    INCBIN "build/gfx/items/0/26.2bpp"
    INCBIN "build/gfx/items/0/27.2bpp"
    INCBIN "build/gfx/items/0/28.2bpp"
    INCBIN "build/gfx/items/0/29.2bpp"
    INCBIN "build/gfx/items/0/30.2bpp"
    INCBIN "build/gfx/items/0/31.2bpp"
    INCBIN "build/gfx/items/0/32.2bpp"
    INCBIN "build/gfx/items/0/33.2bpp"
PauseMenu_Items0_END::

SECTION "Item Graphics Bank 1", ROMX[$4000], BANK[$2C]
PauseMenu_Items1::
	INCBIN "build/gfx/items/1/0.2bpp"
	INCBIN "build/gfx/items/1/1.2bpp"
	INCBIN "build/gfx/items/1/2.2bpp"
	INCBIN "build/gfx/items/1/3.2bpp"
	INCBIN "build/gfx/items/1/4.2bpp"
	INCBIN "build/gfx/items/1/5.2bpp"
	INCBIN "build/gfx/items/1/6.2bpp"
	INCBIN "build/gfx/items/1/7.2bpp"
	INCBIN "build/gfx/items/1/8.2bpp"
	INCBIN "build/gfx/items/1/9.2bpp"
	INCBIN "build/gfx/items/1/10.2bpp"
	INCBIN "build/gfx/items/1/11.2bpp"
	INCBIN "build/gfx/items/1/12.2bpp"
	INCBIN "build/gfx/items/1/13.2bpp"
	INCBIN "build/gfx/items/1/14.2bpp"
	INCBIN "build/gfx/items/1/15.2bpp"
	INCBIN "build/gfx/items/1/16.2bpp"
	INCBIN "build/gfx/items/1/17.2bpp"
	INCBIN "build/gfx/items/1/18.2bpp"
	INCBIN "build/gfx/items/1/19.2bpp"
	INCBIN "build/gfx/items/1/20.2bpp"
	INCBIN "build/gfx/items/1/21.2bpp"
	INCBIN "build/gfx/items/1/22.2bpp"
	INCBIN "build/gfx/items/1/23.2bpp"
	INCBIN "build/gfx/items/1/24.2bpp"
	INCBIN "build/gfx/items/1/25.2bpp"
	INCBIN "build/gfx/items/1/26.2bpp"
	INCBIN "build/gfx/items/1/27.2bpp"
	INCBIN "build/gfx/items/1/28.2bpp"
	INCBIN "build/gfx/items/1/29.2bpp"
	INCBIN "build/gfx/items/1/30.2bpp"
	INCBIN "build/gfx/items/1/31.2bpp"
	INCBIN "build/gfx/items/1/32.2bpp"
	INCBIN "build/gfx/items/1/33.2bpp"
PauseMenu_Items1_END::