SECTION "SGB Attribute Data (Speed Version)", ROMX[$6ED8], BANK[$3]
SGB_AttrFileData::
    INCBIN "build/versions/speed/gfx/sgb/attrfile/00.atf"
    INCBIN "build/versions/speed/gfx/sgb/attrfile/01.atf"
    INCBIN "build/versions/speed/gfx/title/sgb.atf"
    INCBIN "build/gfx/menu/titlemenu.atf"
    INCBIN "build/components/status/status_screen.atf"
    INCBIN "build/versions/speed/gfx/sgb/attrfile/05.atf"
    INCBIN "build/versions/speed/gfx/sgb/attrfile/06.atf"
    INCBIN "build/versions/speed/gfx/sgb/attrfile/07.atf"
    INCBIN "build/versions/speed/gfx/sgb/attrfile/08.atf"
    INCBIN "build/versions/speed/gfx/sgb/attrfile/09.atf"
    INCBIN "build/versions/speed/gfx/sgb/attrfile/0a.atf"
    INCBIN "build/versions/speed/gfx/sgb/attrfile/0b.atf"
    INCBIN "build/versions/speed/gfx/sgb/attrfile/0c.atf"
    INCBIN "build/versions/speed/gfx/sgb/attrfile/0d.atf"
    INCBIN "build/versions/speed/gfx/sgb/attrfile/0e.atf"
    INCBIN "build/versions/speed/gfx/sgb/attrfile/0f.atf"
    INCBIN "build/versions/speed/gfx/sgb/attrfile/10.atf"
    INCBIN "build/versions/speed/gfx/sgb/attrfile/11.atf"
    INCBIN "build/versions/speed/gfx/sgb/attrfile/12.atf"